NumPy (Numerical Python) is a Python library that provides support for efficient numerical operations on
large, multi-dimensional arrays and serves as a fundamental building block for data analysis in Python. The
conventional alias for importing NumPy is np. In other words, NumPy is imported as import numpy as np.
NumPy implements the ndarray object, which allows the creation of a multi-dimensional array of
homogeneous data types (columns with the same data type) and efficient data processing. An ndarray object
can have any number of dimensions and can store elements of various numeric data types. To create a NumPy
ndarray object, one of the following options can be used:


• Creating an ndarray by converting a Python list or tuple using the np.array() function.


• Using built-in functions like np.zeros() and np.ones() for creating an array of all 0's or all 1's,
respectively.


• Generating an array with random numbers using np.random.rand(n, m), where n and m are the
number of rows and columns, respectively.


• Loading data from a file. Ex: np.genfromtxt('data.csv', delimiter=',')

In [2]:
import numpy as np 


->how to create arrays using numpy

In [ ]:
# 1D arrays
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
# 2d array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) #1 roe and 5 columns 

array([[1, 2, 3, 4, 5]])

In [3]:
# 2d array
arr2 = np.array([[1,2,9,5,5],[2,3,4,6,7]])
print(arr2)
print(arr2.shape)

[[1 2 9 5 5]
 [2 3 4 6 7]]
(2, 5)


In [ ]:
# How do you reshape a NumPy array? .reshape()
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
# some in built function in mumpy
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# Check Number of Dimensions?
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [22]:
arr3 = np.array([[[1,2,3],[5,6,8]]])
print("Array:\n", arr3) 
print("shape:",arr3.shape)
print("number of dimensions:",arr3.ndim)
print("size(number if elements):",arr3.size)
print("Data Type:",arr3.dtype)
print("Item size (in bytes):",arr3.itemsize)

Array:
 [[[1 2 3]
  [5 6 8]]]
shape: (1, 2, 3)
number of dimensions: 3
size(number if elements): 6
Data Type: int64
Item size (in bytes): 8


In [24]:
# numpy vectorized operation 
arr4 = np.array([1,2,3,4,5])
arr5 = np.array([10,20,30,40,50])

# element wise addition 
print("addition:",arr4 + arr5)

# element wise substraction 
print("Substraction:",arr4 - arr5)

# element wise multiplication 
print("multiplication:",arr4 * arr5)

# element wise divison 
print("division:",arr4 / arr5)

addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
multiplication: [ 10  40  90 160 250]
division: [0.1 0.1 0.1 0.1 0.1]


In [26]:
# universal function - function applied on entire array 
arr6= np.array([1,5,9,6,3])

# square root 
print(np.sqrt(arr6))

# Exponential
print(np.exp(arr6))

#sine
print(np.sin(arr6))

# natural log 
print(np.log(arr6))

[1.         2.23606798 3.         2.44948974 1.73205081]
[2.71828183e+00 1.48413159e+02 8.10308393e+03 4.03428793e+02
 2.00855369e+01]
[ 0.84147098 -0.95892427  0.41211849 -0.2794155   0.14112001]
[0.         1.60943791 2.19722458 1.79175947 1.09861229]


In [29]:
# array slicing and Indexing 

arr = np.array([[1,2,3,4],[5,6,7,56],[18,19,10,12]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7 56]
 [18 19 10 12]]


In [31]:
arr[0][0]

np.int64(1)

In [ ]:
arr[1:,2:]

array([[ 7, 56],
       [10, 12]])

In [40]:
print(arr[0])
print("___________________________________________________\n")
print(arr[1])
print("___________________________________________________\n")
print(arr[2])

[1 2 3 4]
___________________________________________________

[ 5  6  7 56]
___________________________________________________

[18 19 10 12]


In [45]:
print(arr[0][1])
print("___________________________________________________\n")
print(arr[1][2])
print("___________________________________________________\n")
print(arr[2][3])

2
___________________________________________________

7
___________________________________________________

12


In [46]:
print(arr[0:])
print("___________________________________________________\n")
print(arr[1:])
print("___________________________________________________\n")
print(arr[2:])

[[ 1  2  3  4]
 [ 5  6  7 56]
 [18 19 10 12]]
___________________________________________________

[[ 5  6  7 56]
 [18 19 10 12]]
___________________________________________________

[[18 19 10 12]]


In [58]:
print(arr[0:,1:])
print("___________________________________________________\n")
print(arr[1:,2:])
print("___________________________________________________\n")
print(arr[2:])

[[ 2  3  4]
 [ 6  7 56]
 [19 10 12]]
___________________________________________________

[[ 7 56]
 [10 12]]
___________________________________________________

[[18 19 10 12]]


In [59]:
# modifying array elemens 
arr[0,2] = 200
print(arr)

[[  1   2 200   4]
 [  5   6   7  56]
 [ 18  19  10  12]]


In [60]:
arr[1:]=100
print(arr)

[[  1   2 200   4]
 [100 100 100 100]
 [100 100 100 100]]


## Matrix Inversion in NumPy?

 process of finding the inverse of a square matrix. The identity matrix is produced when multiplying the original matrix by the inverse of the matrix. In other words, if A is a square matrix and A^(-1) is its inverse, then A * A^(-1) = I, where I is the identity matrix.

NumPy provides a convenient function called numpy.linalg.inv() to compute the inverse of a square matrix. Here's how you can use it:






In [30]:
import numpy as np

# Define a square matrix
A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

# Calculate the inverse of the matrix
A_inverse = np.linalg.inv(A)

# Print results
print("Original Matrix:\n", A)
print("Inverse Matrix:\n", A_inverse)

Original Matrix:
 [[1 2 3]
 [0 1 4]
 [5 6 0]]
Inverse Matrix:
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


## multidimensional array to 1D array.

You can convert a multidimensional array to a 1D array which is also known as flattening the array in NumPy using various methods. Two common methods are using for the Convert a multidimensional array to 1D array.

In [32]:
# Create a multidimensional array
multidimensional_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Use the flatten() method to convert it to a 1D array
one_dimensional_array = multidimensional_array.flatten()

print("one dimensional array", one_dimensional_array)

one dimensional array [1 2 3 4 5 6 7 8 9]


In [34]:
# Create a multidimensional array
multidimensional_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Use the ravel() method to convert it to a 1D array
one_dimensional_array = multidimensional_array.ravel()

print("one dimensional array", one_dimensional_array)

one dimensional array [1 2 3 4 5 6 7 8 9]


In [33]:
# statisticalconcepts- Normalization
# to have a mean of 0 and standard deviation of 1 
data = np.array([1,2,3,4,5])

mean = np.mean(data)
std_dev =  np.std(data)

# normalization the data
normalized_Data = (data - mean ) / std_dev
print("normalized data:", normalized_Data)



normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [67]:
# mean 
mean = np.mean(data)
print("mean",mean)

# median
median = np.median(data)
print("median",median)

# standard deviation
std_dev = np.std(data)
print("standard deviation",std_dev)

# variance 
varience = np.var(data)
print("variance :", varience)

mean 3.0
median 3.0
standard deviation 1.4142135623730951
variance : 2.0


In [72]:
#  logical operation 
data1 = np.array([1,2,3,4,5,6,7,8,9,10])
data1[(data1>5) & (data1<=8)]

array([6, 7, 8])

# How to generate random numbers with NumPy?


NumPy provides a wide range of functions for generating random numbers. You can generate random numbers from various probability distributions, set seeds for reproducibility and more. Here are some common ways to generate random numbers with NumPy:

## 1. Using np.random.rand()

Generating a Random Float between 0 and 1 using np.random.rand()

In [23]:
random_float = np.random.rand(4,4)
print(random_float)

[[0.07292194 0.4137425  0.57418681 0.08596755]
 [0.76649191 0.07809681 0.13549561 0.90551285]
 [0.14841364 0.39648253 0.5251815  0.43167145]
 [0.52331847 0.70757396 0.57391935 0.08332635]]


## 2. Using np.random.randint()

Generating a Random Integer within a Range using np.random.randint().

In [21]:
random_integer = np.random.randint(3,size=(3,3))
print(random_integer)

[[1 1 1]
 [2 2 2]
 [1 2 1]]


## 3.Using np.random.randn()

In [25]:
random_float = np.random.randn(2,5)
print(random_float)

[[ 0.77234298 -0.17847276  1.79742051  0.03497425 -0.35306149]
 [ 0.62481712 -0.16323069  0.3475302  -1.26262988  0.83625322]]


##  11. How can you concatenate two NumPy arrays vertically?
We can concatenate two NumPy arrays vertically (along the rows) using the np.vstack() function or the np.concatenate() function with the axis parameter set to 0. Here's how to do it with both methods:

In [26]:
array1 = np.array([[11,22,33],[44,55,66],[77,88,99]])
array2 = np.array([[21,22,23],[31,32,33],[41,42,43]])
array= np.vstack((array1, array2))

In [27]:
print(array)

[[11 22 33]
 [44 55 66]
 [77 88 99]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [28]:
array_new= np.concatenate((array1, array2), axis=0)

In [29]:
print(array_new)

[[11 22 33]
 [44 55 66]
 [77 88 99]
 [21 22 23]
 [31 32 33]
 [41 42 43]]
