# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [1]:
import numpy as np

In [6]:
# 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.
arr1 = np.random.randint(20,size=(5,5))
arr1


array([[ 9, 13,  9, 11, 17],
       [19, 15, 14, 19,  1],
       [11, 12,  9,  8,  2],
       [ 0,  4,  4, 15,  1],
       [ 7, 14, 15,  4,  3]], dtype=int32)

In [7]:
arr1[0:,3] = 1
arr1

array([[ 9, 13,  9,  1, 17],
       [19, 15, 14,  1,  1],
       [11, 12,  9,  1,  2],
       [ 0,  4,  4,  1,  1],
       [ 7, 14, 15,  1,  3]], dtype=int32)

In [12]:
arr2 = np.random.randint(16,size=(4,4))
np.fill_diagonal(arr2, 0)
arr2

array([[ 0, 15,  1,  9],
       [ 1,  0,  1,  2],
       [ 0,  4,  0, 10],
       [13,  0, 14,  0]], dtype=int32)

## Assignment 2
1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [16]:
arr3 = np.arange(1,37).reshape(6,6)
arr3

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [17]:
print(arr3[2:5,1:4])

[[14 15 16]
 [20 21 22]
 [26 27 28]]


In [18]:
arr4 = np.random.randint(1, 100, (5, 5))
print("Original Array:\n", arr4)

Original Array:
 [[26 62 33 43 78]
 [63 76  9 64 81]
 [80 39 79 70  6]
 [32 45 69 75 53]
 [77 77 40 46 37]]


In [23]:
border_element = np.concatenate([arr4[0, :], arr4[-1, :], arr4[1:-1,0], arr4[1:-1,-1]]
)

In [24]:
print(border_element)

[26 62 33 43 78 77 77 40 46 37 63 80 32 81  6 53]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [ ]:
arr5 = np.random.randint(1, 100, (3,4))
arr6 = np.random.randint(1, 100, (3,4))
print(arr5)
print(arr6)

array([[94, 42, 80,  3],
       [75, 37, 34, 92],
       [ 2, 80,  5, 26]], dtype=int32)

In [28]:
arr_Addition = arr5 + arr6
arr_Substraction = arr5 - arr6
arr_Multiplication = arr5 * arr6
arr_Divison = arr5 / arr6

print('ADDITION:\n',arr_Addition)
print('SUBSTRACTION:\n',arr_Substraction)
print('MULTIPLICATION:\n',arr_Multiplication)
print('DIVISION:\n',arr_Divison)

ADDITION:
 [[154  51 179   9]
 [174 114  87  93]
 [ 90 114  60 124]]
SUBSTRACTION:
 [[ 34  33 -19  -3]
 [-24 -40 -19  91]
 [-86  46 -50 -72]]
MULTIPLICATION:
 [[5640  378 7920   18]
 [7425 2849 1802   92]
 [ 176 2720  275 2548]]
DIVISION:
 [[1.56666667e+00 4.66666667e+00 8.08080808e-01 5.00000000e-01]
 [7.57575758e-01 4.80519481e-01 6.41509434e-01 9.20000000e+01]
 [2.27272727e-02 2.35294118e+00 9.09090909e-02 2.65306122e-01]]


In [29]:
arr7 = np.arange(1,17).reshape(4,4)
arr7

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [33]:
print(arr7[0, :].sum())
print(arr7[1, :].sum())
print(arr7[2, :].sum())
print(arr7[3, :].sum())

10
26
42
58


In [35]:
print(arr7[:, 0].sum())
print(arr7[:, 1].sum())
print(arr7[:, 2].sum())
print(arr7[:, 3].sum())

28
32
36
40


In [36]:
col_sum = np.sum(arr7, axis=0)
print("Column-wise Sum:", col_sum)


Column-wise Sum: [28 32 36 40]


In [38]:
row_sum = np.sum(arr7, axis=1)
print("Row-wise Sum:", row_sum)


Row-wise Sum: [10 26 42 58]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [ ]:
arr8 = np.random.randint(1, 100, (5,5))
print('ARRAY:\n',arr8)


ARRAY:
 [[28 49 80 59 85]
 [35  9 18 61 22]
 [26 59 69 95 19]
 [16 44 44 94 87]
 [15 33  2 15 88]]
MEAN:
 46.08


In [50]:
print('MEAN:\n',np.mean(arr8))
print('STANDARD DEVIATION:\n',np.std(arr8))
print('VARIENCE:\n',np.var(arr8))

MEAN:
 46.08
STANDARD DEVIATION:
 29.09696891430446
VARIENCE:
 846.6336


In [52]:
arr9 = np.random.randint(1, 10, (3,3))
arr9

array([[4, 8, 6],
       [5, 1, 5],
       [7, 4, 4]], dtype=int32)

In [53]:
mean = np.mean(arr9)
standard_deviation = np.std(arr9)

normalized_data = (arr9 - mean)/ standard_deviation
print("normalized data: \n", normalized_data)

normalized data: 
 [[-0.46499055  1.62746694  0.58123819]
 [ 0.05812382 -2.03433368  0.05812382]
 [ 1.10435257 -0.46499055 -0.46499055]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [ ]:

# Create a 3x3 array with random integers between 1 and 10
arr_2d = np.random.randint(1, 11, size=(3, 3))
print("Original 2D array:\n", arr_2d)

# Create a 1D array of shape (3,)
arr_1d = np.array([1, 2, 3])
print("1D array to add:\n", arr_1d)

# Add 1D array to each row using broadcasting
result = arr_2d + arr_1d
print("Result after broadcasting addition:\n", result)


Original 2D array:
 [[10  5  8]
 [ 2  6  9]
 [ 9  8  7]]
1D array to add:
 [1 2 3]
Result after broadcasting addition:
 [[11  7 11]
 [ 3  8 12]
 [10 10 10]]


In [55]:
# Create a 4x4 array with random integers between 1 and 10
arr_2d_col = np.random.randint(1, 11, size=(4, 4))
print("Original 4x4 array:\n", arr_2d_col)

# Create a 1D array of shape (4,)
arr_1d_col = np.array([1, 2, 3, 4])
print("1D array to subtract:\n", arr_1d_col)

# Subtract 1D array from each column using broadcasting
result_col = arr_2d_col - arr_1d_col.reshape(-1, 1)  # reshape to (4,1)
print("Result after broadcasting subtraction:\n", result_col)


Original 4x4 array:
 [[10 10  8  8]
 [ 1  4  2  9]
 [ 8  6  8  5]
 [ 2  5  9  8]]
1D array to subtract:
 [1 2 3 4]
Result after broadcasting subtraction:
 [[ 9  9  7  7]
 [-1  2  0  7]
 [ 5  3  5  2]
 [-2  1  5  4]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [56]:
# Create a 3x3 matrix with random integers between 1 and 10
matrix = np.random.randint(1, 11, size=(3, 3))
print("Matrix:\n", matrix)

# Compute determinant
det = np.linalg.det(matrix)
print("\nDeterminant:", det)

# Compute inverse (only if determinant is not zero)
if det != 0:
    inv = np.linalg.inv(matrix)
    print("\nInverse:\n", inv)
else:
    print("\nMatrix is singular, inverse does not exist.")

# Compute eigenvalues
eigvals = np.linalg.eigvals(matrix)
print("\nEigenvalues:\n", eigvals)


Matrix:
 [[10  6 10]
 [ 4  7 10]
 [ 3  6  5]]

Determinant: -159.99999999999994

Inverse:
 [[ 0.15625 -0.1875   0.0625 ]
 [-0.0625  -0.125    0.375  ]
 [-0.01875  0.2625  -0.2875 ]]

Eigenvalues:
 [19.47250169  4.39644402 -1.86894571]


In [57]:
# Create two arrays
A = np.random.randint(1, 11, size=(2, 3))
B = np.random.randint(1, 11, size=(3, 2))

print("Matrix A (2x3):\n", A)
print("\nMatrix B (3x2):\n", B)

# Perform matrix multiplication
C = np.matmul(A, B)  # or A @ B
print("\nResult of A x B (2x2):\n", C)


Matrix A (2x3):
 [[8 2 7]
 [6 9 4]]

Matrix B (3x2):
 [[6 5]
 [2 7]
 [3 8]]

Result of A x B (2x2):
 [[ 73 110]
 [ 66 125]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [61]:
# Create array from 1 to 9
arr10 = np.arange(1, 10).reshape(3, 3)
print("Original array:\n", arr10)

# Reshape to (1, 9)
arr_row = arr10.reshape(1, 9)
print("\nReshaped to (1, 9):\n", arr_row)

# Reshape to (9, 1)
arr_col = arr10.reshape(9, 1)
print("\nReshaped to (9, 1):\n", arr_col)


Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Reshaped to (1, 9):
 [[1 2 3 4 5 6 7 8 9]]

Reshaped to (9, 1):
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [60]:
arr11 = np.random.randint(1, 21, size=(5, 5))
print("\nOriginal 5x5 array:\n", arr11)

# Flatten
flat = arr11.flatten()
print("\nFlattened array:\n", flat)

# Reshape back to (5,5)
reshaped = flat.reshape(5, 5)
print("\nReshaped back to (5,5):\n", reshaped)



Original 5x5 array:
 [[12  8 17 14 10]
 [20  2  6 11  6]
 [ 4  3  6 16 10]
 [13 19 12 10  4]
 [ 8 12  6  4 17]]

Flattened array:
 [12  8 17 14 10 20  2  6 11  6  4  3  6 16 10 13 19 12 10  4  8 12  6  4
 17]

Reshaped back to (5,5):
 [[12  8 17 14 10]
 [20  2  6 11  6]
 [ 4  3  6 16 10]
 [13 19 12 10  4]
 [ 8 12  6  4 17]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [62]:
arr12 = np.random.randint(1, 21, size=(5, 5))
print("\n5x5 Array:\n", arr12)

# Corners: top-left, top-right, bottom-left, bottom-right
corners = arr12[[0,0,4,4], [0,4,0,4]]
print("\nCorners of the array:", corners)


5x5 Array:
 [[ 2  9 20 11  3]
 [19  6  7  6 20]
 [ 9  3  7 19 11]
 [13 20  3 11 20]
 [10  2 13 18  2]]

Corners of the array: [ 2  3 10  2]


In [63]:
arr14 = np.random.randint(5, 21, size=(4, 4))
print("\nOriginal 4x4 array:\n", arr14)

# Set elements greater than 10 to 10
arr14[arr14 > 10] = 10
print("\nAfter capping values >10:\n", arr14)



Original 4x4 array:
 [[11  5 20 12]
 [10  7 14  5]
 [11 17 12  5]
 [13 13  6 17]]

After capping values >10:
 [[10  5 10 10]
 [10  7 10  5]
 [10 10 10  5]
 [10 10  6 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [64]:
# Define structured dtype
dtype = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]

# Create array
data = np.array([('Alice', 25, 55.0),
                 ('Bob', 22, 70.5),
                 ('Charlie', 28, 68.0)], dtype=dtype)

print("\nStructured Array:\n", data)

# Sort by age
sorted_by_age = np.sort(data, order='age')
print("\nSorted by age:\n", sorted_by_age)



Structured Array:
 [('Alice', 25, 55. ) ('Bob', 22, 70.5) ('Charlie', 28, 68. )]

Sorted by age:
 [('Bob', 22, 70.5) ('Alice', 25, 55. ) ('Charlie', 28, 68. )]


In [65]:
dtype_points = [('x', 'i4'), ('y', 'i4')]
points = np.array([(1,2), (4,6), (0,0)], dtype=dtype_points)
print("\nPoints:\n", points)

# Compute pairwise Euclidean distances
for i in range(len(points)):
    for j in range(i+1, len(points)):
        dist = np.sqrt((points[i]['x'] - points[j]['x'])**2 + (points[i]['y'] - points[j]['y'])**2)
        print(f"Distance between point {i} and {j}: {dist}")



Points:
 [(1, 2) (4, 6) (0, 0)]
Distance between point 0 and 1: 5.0
Distance between point 0 and 2: 2.23606797749979
Distance between point 1 and 2: 7.211102550927978


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [66]:
arr15 = np.random.randint(5, 21, size=(4, 4))
print("\nOriginal 4x4 array:\n", arr15)

masked_arr = np.ma.masked_greater(arr15, 10)
print("\nMasked array:\n", masked_arr)

# Sum of unmasked elements
sum_unmasked = masked_arr.sum()
print("\nSum of unmasked elements:", sum_unmasked)



Original 4x4 array:
 [[ 8 17 19 20]
 [13  7 11  5]
 [18 20 16 15]
 [20  9  8 19]]

Masked array:
 [[8 -- -- --]
 [-- 7 -- 5]
 [-- -- -- --]
 [-- 9 8 --]]

Sum of unmasked elements: 37


In [67]:
arr16 = np.random.randint(1, 21, size=(3, 3))
print("\nOriginal 3x3 array:\n", arr16)

masked_diag = np.ma.masked_array(arr16, mask=np.eye(3, dtype=bool))
print("\nMasked diagonal array:\n", masked_diag)

# Mean of unmasked elements
mean_unmasked = masked_diag.mean()

# Fill masked elements with mean
filled = masked_diag.filled(mean_unmasked)
print("\nDiagonal replaced with mean:\n", filled)



Original 3x3 array:
 [[18  4  9]
 [ 7 10 16]
 [16  1  6]]

Masked diagonal array:
 [[-- 4 9]
 [7 -- 16]
 [16 1 --]]

Diagonal replaced with mean:
 [[ 8  4  9]
 [ 7  8 16]
 [16  1  8]]
