NumPy (Numerical Python) is a Python library that provides support for efficient numerical operations on
large, multi-dimensional arrays and serves as a fundamental building block for data analysis in Python. The
conventional alias for importing NumPy is np. In other words, NumPy is imported as import numpy as np.
NumPy implements the ndarray object, which allows the creation of a multi-dimensional array of
homogeneous data types (columns with the same data type) and efficient data processing. An ndarray object
can have any number of dimensions and can store elements of various numeric data types. To create a NumPy
ndarray object, one of the following options can be used:


• Creating an ndarray by converting a Python list or tuple using the np.array() function.


• Using built-in functions like np.zeros() and np.ones() for creating an array of all 0's or all 1's,
respectively.


• Generating an array with random numbers using np.random.rand(n, m), where n and m are the
number of rows and columns, respectively.


• Loading data from a file. Ex: np.genfromtxt('data.csv', delimiter=',')

In [2]:
import numpy as np 


In [4]:
# how to create arrays using numpy

# 1D arrays
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
# 2 d array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) #1 roe and 5 columns 

array([[1, 2, 3, 4, 5]])

In [12]:
# 2d array
arr2 = np.array([[1,2,9,5,5],[2,3,4,6,7]])
print(arr2)
arr2.shape

[[1 2 9 5 5]
 [2 3 4 6 7]]


(2, 5)

In [13]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [14]:
# some in built function in mumpy

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# Check Number of Dimensions?
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [22]:
arr3 = np.array([[[1,2,3],[5,6,8]]])
print("Array:\n", arr3) 
print("shape:",arr3.shape)
print("number of dimensions:",arr3.ndim)
print("size(number if elements):",arr3.size)
print("Data Type:",arr3.dtype)
print("Item size (in bytes):",arr3.itemsize)

Array:
 [[[1 2 3]
  [5 6 8]]]
shape: (1, 2, 3)
number of dimensions: 3
size(number if elements): 6
Data Type: int64
Item size (in bytes): 8


In [24]:
# numpy vectorized operation 
arr4 = np.array([1,2,3,4,5])
arr5 = np.array([10,20,30,40,50])

# element wise addition 
print("addition:",arr4 + arr5)

# element wise substraction 
print("Substraction:",arr4 - arr5)

# element wise multiplication 
print("multiplication:",arr4 * arr5)

# element wise divison 
print("division:",arr4 / arr5)

addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
multiplication: [ 10  40  90 160 250]
division: [0.1 0.1 0.1 0.1 0.1]


In [26]:
# universal function - function applied on entire array 
arr6= np.array([1,5,9,6,3])

# square root 
print(np.sqrt(arr6))

# Exponential
print(np.exp(arr6))

#sine
print(np.sin(arr6))

# natural log 
print(np.log(arr6))

[1.         2.23606798 3.         2.44948974 1.73205081]
[2.71828183e+00 1.48413159e+02 8.10308393e+03 4.03428793e+02
 2.00855369e+01]
[ 0.84147098 -0.95892427  0.41211849 -0.2794155   0.14112001]
[0.         1.60943791 2.19722458 1.79175947 1.09861229]


In [29]:
# array slicing and Indexing 

arr = np.array([[1,2,3,4],[5,6,7,56],[18,19,10,12]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7 56]
 [18 19 10 12]]


In [31]:
arr[0][0]

np.int64(1)

In [ ]:
arr[1:,2:]

array([[ 7, 56],
       [10, 12]])

In [40]:
print(arr[0])
print("___________________________________________________\n")
print(arr[1])
print("___________________________________________________\n")
print(arr[2])

[1 2 3 4]
___________________________________________________

[ 5  6  7 56]
___________________________________________________

[18 19 10 12]


In [45]:
print(arr[0][1])
print("___________________________________________________\n")
print(arr[1][2])
print("___________________________________________________\n")
print(arr[2][3])

2
___________________________________________________

7
___________________________________________________

12


In [46]:
print(arr[0:])
print("___________________________________________________\n")
print(arr[1:])
print("___________________________________________________\n")
print(arr[2:])

[[ 1  2  3  4]
 [ 5  6  7 56]
 [18 19 10 12]]
___________________________________________________

[[ 5  6  7 56]
 [18 19 10 12]]
___________________________________________________

[[18 19 10 12]]


In [58]:
print(arr[0:,1:])
print("___________________________________________________\n")
print(arr[1:,2:])
print("___________________________________________________\n")
print(arr[2:])

[[ 2  3  4]
 [ 6  7 56]
 [19 10 12]]
___________________________________________________

[[ 7 56]
 [10 12]]
___________________________________________________

[[18 19 10 12]]


In [59]:
# modifying array elemens 
arr[0,2] = 200
print(arr)

[[  1   2 200   4]
 [  5   6   7  56]
 [ 18  19  10  12]]


In [60]:
arr[1:]=100
print(arr)

[[  1   2 200   4]
 [100 100 100 100]
 [100 100 100 100]]


In [65]:
# statisticalconcepts- Normalization
# to have a mean of 0 and standard deviation of 1 
data = np.array([1,2,3,4,5])

mean = np.mean(data)
std_dev =  np.std(data)

# normalization the data
normalized_Data = (data - mean ) / std_dev
print("normalized data:", normalized_Data)



normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [67]:
# mean 
mean = np.mean(data)
print("mean",mean)

# median
median = np.median(data)
print("median",median)

# standard deviation
std_dev = np.std(data)
print("standard deviation",std_dev)

# variance 
varience = np.var(data)
print("variance :", varience)

mean 3.0
median 3.0
standard deviation 1.4142135623730951
variance : 2.0


In [72]:
#  logical operation 
data1 = np.array([1,2,3,4,5,6,7,8,9,10])
data1[(data1>5) & (data1<=8)]

array([6, 7, 8])